export const MUTATION_AND_QUERY_KEYS = {
  // MUTATIONS
  REGISTER: ['register'],
  LOGIN: ['login'],
  LOGOUT: ['logout'],
  CREATE_VESIOSUUSKUNTA: ['createVesiosuuskunta'],
  CREATE_MEMBER: ['createMember'],
  DELETE_MEMBER: ['deleteMember'],

  // QUERIES
  VESIOSUUSKUNNAT: ['vesiosuuskunnat'],
  VESIOSUUSKUNTA: ['vesiosuuskunta'],
  MEMBERS: ['members'],
};

export const arrayOfNames_debug = [
  {
    lastName: 'Doe',
    firstName: 'John',
    streetAddress: 'Mannerheimintie 30',
    zipCode: '00100',
    city: 'Helsinki',
    phoneNumber: '045 678 9012',
    email: 'john.doe@doemail.com',
    paid: '01/01/1970',
    connectionPointNumber: 'K111',
    comment: 'Testi Kommentti',
  },
  {
    lastName: 'Doe',
    firstName: 'John',
    streetAddress: 'Mannerheimintie 30',
    zipCode: '00100',
    city: 'Helsinki',
    phoneNumber: '045 678 9012',
    email: 'john.doe@doemail.com',
    paid: '01/01/1970',
    connectionPointNumber: 'K111',
    comment: 'Testi Kommentti',
  },
  {
    lastName: 'Doe',
    firstName: 'John',
    streetAddress: 'Mannerheimintie 30',
    zipCode: '00100',
    city: 'Helsinki',
    phoneNumber: '045 678 9012',
    email: 'john.doe@doemail.com',
    paid: '01/01/1970',
    connectionPointNumber: 'K111',
    comment: 'Testi Kommentti',
  },
  {
    lastName: 'Doe',
    firstName: 'John',
    streetAddress: 'Mannerheimintie 30',
    zipCode: '00100',
    city: 'Helsinki',
    phoneNumber: '045 678 9012',
    email: 'john.doe@doemail.com',
    paid: '01/01/1970',
    connectionPointNumber: 'K111',
    comment: 'Testi Kommentti',
  },
  {
    lastName: 'Doe',
    firstName: 'John',
    streetAddress: 'Mannerheimintie 30',
    zipCode: '00100',
    city: 'Helsinki',
    phoneNumber: '045 678 9012',
    email: 'john.doe@doemail.com',
    paid: '01/01/1970',
    connectionPointNumber: 'K111',
    comment: 'Testi Kommentti',
  },
  {
    lastName: 'Doe',
    firstName: 'John',
    streetAddress: 'Mannerheimintie 30',
    zipCode: '00100',
    city: 'Helsinki',
    phoneNumber: '045 678 9012',
    email: 'john.doe@doemail.com',
    paid: '01/01/1970',
    connectionPointNumber: 'K111',
    comment: 'Testi Kommentti',
  },
  {
    lastName: 'Doe',
    firstName: 'John',
    streetAddress: 'Mannerheimintie 30',
    zipCode: '00100',
    city: 'Helsinki',
    phoneNumber: '045 678 9012',
    email: 'john.doe@doemail.com',
    paid: '01/01/1970',
    connectionPointNumber: 'K111',
    comment: 'Testi Kommentti',
  },
  {
    lastName: 'Doe',
    firstName: 'John',
    streetAddress: 'Mannerheimintie 30',
    zipCode: '00100',
    city: 'Helsinki',
    phoneNumber: '045 678 9012',
    email: 'john.doe@doemail.com',
    paid: '01/01/1970',
    connectionPointNumber: 'K111',
    comment: 'Testi Kommentti',
  },
  {
    lastName: 'Doe',
    firstName: 'John',
    streetAddress: 'Mannerheimintie 30',
    zipCode: '00100',
    city: 'Helsinki',
    phoneNumber: '045 678 9012',
    email: 'john.doe@doemail.com',
    paid: '01/01/1970',
    connectionPointNumber: 'K111',
    comment: 'Testi Kommentti',
  },
];
